### ISSUE TITLE
Is take measurement correct?

### ISSUE THREAD

**Issue by simplect** [kevinlutzer/Arduino-PM1006K#2]
Hi!

Playing with this library, arduino uno and the IKEA vindrikting insides. The measurements don't seem to make that much sense. Very high pm1.0 and always zero PM10. I spotted that the 13 and 12 are switched, is that correct? 

``` 
 this->_lastPM2_5 = (rxBuf[5] << 8) | rxBuf[6];
  this->_lastPM1_0 = (rxBuf[9] << 8) | rxBuf[10];
  this->_lastPM10 = (rxBuf[13] << 8) | rxBuf[12]; // Should this be first 12 then 13?
```

**Comment by kevinlutzer** [comment]
Hi 👋 

From the docs: 

``` text
Read measures result of particles:
Send: 11 01 02 EC
Response: 16 0d 02 DF1- DF4 DF5- DF8 DF9- DF12 [CS]
Note: PM2.5(μg/m³)= DF3*256+DF4
PM1.0(μg/m³) = DF7*256^1 + DF8
PM10(μg/m³) = DF11*256^1 + DF12
```

You are right there is an issue here but I think it's because I am indexing at position 12 for the first byte of `PM10` instead of position 14. 

Thanks for the catch! 😃
